chore(deps): Lock aioredis to <2
`aioredis` v2.0.0 has just been released:
https://pypi.org/project/aioredis/2.0.0/

It breaks `aioredlock` with the following errors:
```
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
AttributeError: module 'aioredis' has no attribute 'errors'
```

I propose to lock the `aioredis` version `aioredlock` requires to
<2 (latest before v2.0.0 is v1.3.1).